<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LegacyRegiaoSeeder extends Seeder
{
    public function run()
    {
        $rows = [
[
                    'id_pais' => 1,
                    'nome_pais' => 'AFEGANISTÃO',
                    'name_pais' => 'AFGHANISTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 2,
                    'nome_pais' => 'ACROTÍRI E DECELIA',
                    'name_pais' => 'AKROTIRI E DEKÉLIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 3,
                    'nome_pais' => 'ÁFRICA DO SUL',
                    'name_pais' => 'SOUTH AFRICA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 4,
                    'nome_pais' => 'ALBÂNIA',
                    'name_pais' => 'ALBANIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 5,
                    'nome_pais' => 'ALEMANHA',
                    'name_pais' => 'GERMANY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => 'Europe/Berlin',
                ],
[
                    'id_pais' => 6,
                    'nome_pais' => 'AMERICAN SAMOA',
                    'name_pais' => 'AMERICAN SAMOA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 7,
                    'nome_pais' => 'ANDORRA',
                    'name_pais' => 'ANDORRA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 8,
                    'nome_pais' => 'ANGOLA',
                    'name_pais' => 'ANGOLA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 9,
                    'nome_pais' => 'ANGUILLA',
                    'name_pais' => 'ANGUILLA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 10,
                    'nome_pais' => 'ANTÍGUA E BARBUDA',
                    'name_pais' => 'ANTIGUA AND BARBUDA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 11,
                    'nome_pais' => 'ANTILHAS NEERLANDESAS',
                    'name_pais' => 'NETHERLANDS ANTILLES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 12,
                    'nome_pais' => 'ARÁBIA SAUDITA',
                    'name_pais' => 'SAUDI ARABIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 13,
                    'nome_pais' => 'ARGÉLIA',
                    'name_pais' => 'ALGERIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 14,
                    'nome_pais' => 'ARGENTINA',
                    'name_pais' => 'ARGENTINA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 15,
                    'nome_pais' => 'ARMÉNIA',
                    'name_pais' => 'ARMENIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 16,
                    'nome_pais' => 'ARUBA',
                    'name_pais' => 'ARUBA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 17,
                    'nome_pais' => 'AUSTRÁLIA',
                    'name_pais' => 'AUSTRALIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 18,
                    'nome_pais' => 'ÁUSTRIA',
                    'name_pais' => 'AUSTRIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 19,
                    'nome_pais' => 'AZERBAIJÃO',
                    'name_pais' => 'AZERBAIJAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 20,
                    'nome_pais' => 'BAHAMAS',
                    'name_pais' => 'BAHAMAS, THE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 21,
                    'nome_pais' => 'BANGLADECHE',
                    'name_pais' => 'BANGLADESH',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 22,
                    'nome_pais' => 'BARBADOS',
                    'name_pais' => 'BARBADOS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 23,
                    'nome_pais' => 'BARÉM',
                    'name_pais' => 'BAHRAIN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 24,
                    'nome_pais' => 'BASSAS DA ÍNDIA',
                    'name_pais' => 'BASSAS DA INDIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 25,
                    'nome_pais' => 'BÉLGICA',
                    'name_pais' => 'BELGIUM',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 26,
                    'nome_pais' => 'BELIZE',
                    'name_pais' => 'BELIZE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 27,
                    'nome_pais' => 'BENIM',
                    'name_pais' => 'BENIN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 28,
                    'nome_pais' => 'BERMUDAS',
                    'name_pais' => 'BERMUDA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 29,
                    'nome_pais' => 'BIELORRÚSSIA',
                    'name_pais' => 'BELARUS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 30,
                    'nome_pais' => 'BOLÍVIA',
                    'name_pais' => 'BOLIVIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 31,
                    'nome_pais' => 'BÓSNIA E HERZEGOVINA',
                    'name_pais' => 'BOSNIA AND HERZEGOVINA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 32,
                    'nome_pais' => 'BOTSUANA',
                    'name_pais' => 'BOTSWANA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 33,
                    'nome_pais' => 'BRASIL',
                    'name_pais' => 'BRAZIL',
                    'moeda_sigla' => 'R$',
                    'status' => 1,
                    'timezone' => 'America/Sao_Paulo',
                ],
[
                    'id_pais' => 34,
                    'nome_pais' => 'BRUNEI DARUSSALAM',
                    'name_pais' => 'BRUNEI DARUSSALAM',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 35,
                    'nome_pais' => 'BULGÁRIA',
                    'name_pais' => 'BULGARIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 36,
                    'nome_pais' => 'BURQUINA FASO',
                    'name_pais' => 'BURKINA FASO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 37,
                    'nome_pais' => 'BURUNDI',
                    'name_pais' => 'BURUNDI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 38,
                    'nome_pais' => 'BUTÃO',
                    'name_pais' => 'BHUTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 39,
                    'nome_pais' => 'CABO VERDE',
                    'name_pais' => 'CAPE VERDE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 40,
                    'nome_pais' => 'CAMARÕES',
                    'name_pais' => 'CAMEROON',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 41,
                    'nome_pais' => 'CAMBOJA',
                    'name_pais' => 'CAMBODIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 42,
                    'nome_pais' => 'CANADÁ',
                    'name_pais' => 'CANADA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 43,
                    'nome_pais' => 'CATAR',
                    'name_pais' => 'QATAR',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 44,
                    'nome_pais' => 'CAZAQUISTÃO',
                    'name_pais' => 'KAZAKHSTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 45,
                    'nome_pais' => 'CENTRO-AFRICANA REPÚBLICA',
                    'name_pais' => 'CENTRAL AFRICAN REPUBLIC',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 46,
                    'nome_pais' => 'CHADE',
                    'name_pais' => 'CHAD',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 47,
                    'nome_pais' => 'CHILE',
                    'name_pais' => 'CHILE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 48,
                    'nome_pais' => 'CHINA',
                    'name_pais' => 'CHINA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 49,
                    'nome_pais' => 'CHIPRE',
                    'name_pais' => 'CYPRUS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 50,
                    'nome_pais' => 'COLÔMBIA',
                    'name_pais' => 'COLOMBIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 51,
                    'nome_pais' => 'COMORES',
                    'name_pais' => 'COMOROS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 52,
                    'nome_pais' => 'CONGO',
                    'name_pais' => 'CONGO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 53,
                    'nome_pais' => 'CONGO REPÚBLICA DEMOCRÁTICA',
                    'name_pais' => 'CONGO DEMOCRATIC REPUBLIC',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 54,
                    'nome_pais' => 'COREIA DO NORTE',
                    'name_pais' => 'KOREA NORTH',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 55,
                    'nome_pais' => 'COREIA DO SUL',
                    'name_pais' => 'KOREA SOUTH',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 56,
                    'nome_pais' => 'COSTA DO MARFIM',
                    'name_pais' => 'IVORY COAST',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 57,
                    'nome_pais' => 'COSTA RICA',
                    'name_pais' => 'COSTA RICA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 58,
                    'nome_pais' => 'CROÁCIA',
                    'name_pais' => 'CROATIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 59,
                    'nome_pais' => 'CUBA',
                    'name_pais' => 'CUBA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 60,
                    'nome_pais' => 'DINAMARCA',
                    'name_pais' => 'DENMARK',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 61,
                    'nome_pais' => 'DOMÍNICA',
                    'name_pais' => 'DOMINICA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 62,
                    'nome_pais' => 'EGIPTO',
                    'name_pais' => 'EGYPT',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 63,
                    'nome_pais' => 'EMIRADOS ÁRABES UNIDOS',
                    'name_pais' => 'UNITED ARAB EMIRATES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 64,
                    'nome_pais' => 'EQUADOR',
                    'name_pais' => 'ECUADOR',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 65,
                    'nome_pais' => 'ERITREIA',
                    'name_pais' => 'ERITREA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 66,
                    'nome_pais' => 'ESLOVÁQUIA',
                    'name_pais' => 'SLOVAKIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 67,
                    'nome_pais' => 'ESLOVÉNIA',
                    'name_pais' => 'SLOVENIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 68,
                    'nome_pais' => 'ESPANHA',
                    'name_pais' => 'SPAIN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => 'Europe/Madrid',
                ],
[
                    'id_pais' => 69,
                    'nome_pais' => 'ESTADOS UNIDOS',
                    'name_pais' => 'UNITED STATES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => 'America/New_York',
                ],
[
                    'id_pais' => 70,
                    'nome_pais' => 'ESTÓNIA',
                    'name_pais' => 'ESTONIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 71,
                    'nome_pais' => 'ETIÓPIA',
                    'name_pais' => 'ETHIOPIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 72,
                    'nome_pais' => 'FAIXA DE GAZA',
                    'name_pais' => 'GAZA STRIP',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 73,
                    'nome_pais' => 'FIJI',
                    'name_pais' => 'FIJI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 74,
                    'nome_pais' => 'FILIPINAS',
                    'name_pais' => 'PHILIPPINES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 75,
                    'nome_pais' => 'FINLÂNDIA',
                    'name_pais' => 'FINLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 76,
                    'nome_pais' => 'FRANÇA',
                    'name_pais' => 'FRANCE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 77,
                    'nome_pais' => 'GABÃO',
                    'name_pais' => 'GABON',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 78,
                    'nome_pais' => 'GÂMBIA',
                    'name_pais' => 'GAMBIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 79,
                    'nome_pais' => 'GANA',
                    'name_pais' => 'GHANA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 80,
                    'nome_pais' => 'GEÓRGIA',
                    'name_pais' => 'GEORGIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 81,
                    'nome_pais' => 'GIBRALTAR',
                    'name_pais' => 'GIBRALTAR',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 82,
                    'nome_pais' => 'GRANADA',
                    'name_pais' => 'GRENADA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 83,
                    'nome_pais' => 'GRÉCIA',
                    'name_pais' => 'GREECE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 84,
                    'nome_pais' => 'GRONELÂNDIA',
                    'name_pais' => 'GREENLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 85,
                    'nome_pais' => 'GUADALUPE',
                    'name_pais' => 'GUADELOUPE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 86,
                    'nome_pais' => 'GUAM',
                    'name_pais' => 'GUAM',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 87,
                    'nome_pais' => 'GUATEMALA',
                    'name_pais' => 'GUATEMALA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 88,
                    'nome_pais' => 'GUERNSEY',
                    'name_pais' => 'GUERNSEY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 89,
                    'nome_pais' => 'GUIANA',
                    'name_pais' => 'GUYANA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 90,
                    'nome_pais' => 'GUIANA FRANCESA',
                    'name_pais' => 'FRENCH GUIANA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 91,
                    'nome_pais' => 'GUINÉ',
                    'name_pais' => 'GUINEA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 92,
                    'nome_pais' => 'GUINÉ EQUATORIAL',
                    'name_pais' => 'EQUATORIAL GUINEA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 93,
                    'nome_pais' => 'GUINÉ-BISSAU',
                    'name_pais' => 'GUINEA-BISSAU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 94,
                    'nome_pais' => 'HAITI',
                    'name_pais' => 'HAITI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 95,
                    'nome_pais' => 'HONDURAS',
                    'name_pais' => 'HONDURAS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 96,
                    'nome_pais' => 'HONG KONG',
                    'name_pais' => 'HONG KONG',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 97,
                    'nome_pais' => 'HUNGRIA',
                    'name_pais' => 'HUNGARY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 98,
                    'nome_pais' => 'IÉMEN',
                    'name_pais' => 'YEMEN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 99,
                    'nome_pais' => 'ILHA BOUVET',
                    'name_pais' => 'BOUVET ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 100,
                    'nome_pais' => 'ILHA CHRISTMAS',
                    'name_pais' => 'CHRISTMAS ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 101,
                    'nome_pais' => 'ILHA DE CLIPPERTON',
                    'name_pais' => 'CLIPPERTON ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 102,
                    'nome_pais' => 'ILHA DE JOÃO DA NOVA',
                    'name_pais' => 'JUAN DE NOVA ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 103,
                    'nome_pais' => 'ILHA DE MAN',
                    'name_pais' => 'ISLE OF MAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 104,
                    'nome_pais' => 'ILHA DE NAVASSA',
                    'name_pais' => 'NAVASSA ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 105,
                    'nome_pais' => 'ILHA EUROPA',
                    'name_pais' => 'EUROPA ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 106,
                    'nome_pais' => 'ILHA NORFOLK',
                    'name_pais' => 'NORFOLK ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 107,
                    'nome_pais' => 'ILHA TROMELIN',
                    'name_pais' => 'TROMELIN ISLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 108,
                    'nome_pais' => 'ILHAS ASHMORE E CARTIER',
                    'name_pais' => 'ASHMORE AND CARTIER ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 109,
                    'nome_pais' => 'ILHAS CAIMAN',
                    'name_pais' => 'CAYMAN ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 110,
                    'nome_pais' => 'ILHAS COCOS (KEELING)',
                    'name_pais' => 'COCOS (KEELING) ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 111,
                    'nome_pais' => 'ILHAS COOK',
                    'name_pais' => 'COOK ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 112,
                    'nome_pais' => 'ILHAS DO MAR DE CORAL',
                    'name_pais' => 'CORAL SEA ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 113,
                    'nome_pais' => 'ILHAS FALKLANDS (ILHAS MALVINAS)',
                    'name_pais' => 'FALKLAND ISLANDS (ISLAS MALVINAS)',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 114,
                    'nome_pais' => 'ILHAS FEROE',
                    'name_pais' => 'FAROE ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 115,
                    'nome_pais' => 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL',
                    'name_pais' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 116,
                    'nome_pais' => 'ILHAS MARIANAS DO NORTE',
                    'name_pais' => 'NORTHERN MARIANA ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 117,
                    'nome_pais' => 'ILHAS MARSHALL',
                    'name_pais' => 'MARSHALL ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 118,
                    'nome_pais' => 'ILHAS PARACEL',
                    'name_pais' => 'PARACEL ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 119,
                    'nome_pais' => 'ILHAS PITCAIRN',
                    'name_pais' => 'PITCAIRN ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 120,
                    'nome_pais' => 'ILHAS SALOMÃO',
                    'name_pais' => 'SOLOMON ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 121,
                    'nome_pais' => 'ILHAS SPRATLY',
                    'name_pais' => 'SPRATLY ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 122,
                    'nome_pais' => 'ILHAS VIRGENS AMERICANAS',
                    'name_pais' => 'UNITED STATES VIRGIN ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 123,
                    'nome_pais' => 'ILHAS VIRGENS BRITÂNICAS',
                    'name_pais' => 'BRITISH VIRGIN ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 124,
                    'nome_pais' => 'ÍNDIA',
                    'name_pais' => 'INDIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 125,
                    'nome_pais' => 'INDONÉSIA',
                    'name_pais' => 'INDONESIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 126,
                    'nome_pais' => 'IRÃO',
                    'name_pais' => 'IRAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 127,
                    'nome_pais' => 'IRAQUE',
                    'name_pais' => 'IRAQ',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 128,
                    'nome_pais' => 'IRLANDA',
                    'name_pais' => 'IRELAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 129,
                    'nome_pais' => 'ISLÂNDIA',
                    'name_pais' => 'ICELAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 130,
                    'nome_pais' => 'ISRAEL',
                    'name_pais' => 'ISRAEL',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 131,
                    'nome_pais' => 'ITÁLIA',
                    'name_pais' => 'ITALY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 132,
                    'nome_pais' => 'JAMAICA',
                    'name_pais' => 'JAMAICA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 133,
                    'nome_pais' => 'JAN MAYEN',
                    'name_pais' => 'JAN MAYEN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 134,
                    'nome_pais' => 'JAPÃO',
                    'name_pais' => 'JAPAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 135,
                    'nome_pais' => 'JERSEY',
                    'name_pais' => 'JERSEY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 136,
                    'nome_pais' => 'JIBUTI',
                    'name_pais' => 'DJIBOUTI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 137,
                    'nome_pais' => 'JORDÂNIA',
                    'name_pais' => 'JORDAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 138,
                    'nome_pais' => 'KIRIBATI',
                    'name_pais' => 'KIRIBATI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 139,
                    'nome_pais' => 'KOWEIT',
                    'name_pais' => 'KUWAIT',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 140,
                    'nome_pais' => 'LAOS',
                    'name_pais' => 'LAOS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 141,
                    'nome_pais' => 'LESOTO',
                    'name_pais' => 'LESOTHO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 142,
                    'nome_pais' => 'LETÓNIA',
                    'name_pais' => 'LATVIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 143,
                    'nome_pais' => 'LÍBANO',
                    'name_pais' => 'LEBANON',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 144,
                    'nome_pais' => 'LIBÉRIA',
                    'name_pais' => 'LIBERIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 145,
                    'nome_pais' => 'LÍBIA',
                    'name_pais' => 'LIBYAN ARAB JAMAHIRIYA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 146,
                    'nome_pais' => 'LISTENSTAINE',
                    'name_pais' => 'LIECHTENSTEIN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 147,
                    'nome_pais' => 'LITUÂNIA',
                    'name_pais' => 'LITHUANIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 148,
                    'nome_pais' => 'LUXEMBURGO',
                    'name_pais' => 'LUXEMBOURG',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 149,
                    'nome_pais' => 'MACAU',
                    'name_pais' => 'MACAO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 150,
                    'nome_pais' => 'MACEDÓNIA',
                    'name_pais' => 'MACEDONIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 151,
                    'nome_pais' => 'MADAGÁSCAR',
                    'name_pais' => 'MADAGASCAR',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 152,
                    'nome_pais' => 'MALÁSIA',
                    'name_pais' => 'MALAYSIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 153,
                    'nome_pais' => 'MALAVI',
                    'name_pais' => 'MALAWI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 154,
                    'nome_pais' => 'MALDIVAS',
                    'name_pais' => 'MALDIVES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 155,
                    'nome_pais' => 'MALI',
                    'name_pais' => 'MALI',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 156,
                    'nome_pais' => 'MALTA',
                    'name_pais' => 'MALTA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 157,
                    'nome_pais' => 'MARROCOS',
                    'name_pais' => 'MOROCCO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 158,
                    'nome_pais' => 'MARTINICA',
                    'name_pais' => 'MARTINIQUE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 159,
                    'nome_pais' => 'MAURÍCIA',
                    'name_pais' => 'MAURITIUS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 160,
                    'nome_pais' => 'MAURITÂNIA',
                    'name_pais' => 'MAURITANIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 161,
                    'nome_pais' => 'MAYOTTE',
                    'name_pais' => 'MAYOTTE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 162,
                    'nome_pais' => 'MÉXICO',
                    'name_pais' => 'MEXICO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 163,
                    'nome_pais' => 'MIANMAR',
                    'name_pais' => 'MYANMAR BURMA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 164,
                    'nome_pais' => 'MICRONÉSIA',
                    'name_pais' => 'MICRONESIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 165,
                    'nome_pais' => 'MOÇAMBIQUE',
                    'name_pais' => 'MOZAMBIQUE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 166,
                    'nome_pais' => 'MOLDÁVIA',
                    'name_pais' => 'MOLDOVA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 167,
                    'nome_pais' => 'MÓNACO',
                    'name_pais' => 'MONACO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 168,
                    'nome_pais' => 'MONGÓLIA',
                    'name_pais' => 'MONGOLIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 169,
                    'nome_pais' => 'MONTENEGRO',
                    'name_pais' => 'MONTENEGRO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 170,
                    'nome_pais' => 'MONTSERRAT',
                    'name_pais' => 'MONTSERRAT',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 171,
                    'nome_pais' => 'NAMÍBIA',
                    'name_pais' => 'NAMIBIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 172,
                    'nome_pais' => 'NAURU',
                    'name_pais' => 'NAURU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 173,
                    'nome_pais' => 'NEPAL',
                    'name_pais' => 'NEPAL',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 174,
                    'nome_pais' => 'NICARÁGUA',
                    'name_pais' => 'NICARAGUA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 175,
                    'nome_pais' => 'NÍGER',
                    'name_pais' => 'NIGER',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 176,
                    'nome_pais' => 'NIGÉRIA',
                    'name_pais' => 'NIGERIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 177,
                    'nome_pais' => 'NIUE',
                    'name_pais' => 'NIUE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 178,
                    'nome_pais' => 'NORUEGA',
                    'name_pais' => 'NORWAY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 179,
                    'nome_pais' => 'NOVA CALEDÓNIA',
                    'name_pais' => 'NEW CALEDONIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 180,
                    'nome_pais' => 'NOVA ZELÂNDIA',
                    'name_pais' => 'NEW ZEALAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 181,
                    'nome_pais' => 'OMÃ',
                    'name_pais' => 'OMAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 182,
                    'nome_pais' => 'PAÍSES BAIXOS',
                    'name_pais' => 'NETHERLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 183,
                    'nome_pais' => 'PALAU',
                    'name_pais' => 'PALAU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 184,
                    'nome_pais' => 'PALESTINA',
                    'name_pais' => 'PALESTINE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 185,
                    'nome_pais' => 'PANAMÁ',
                    'name_pais' => 'PANAMA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 186,
                    'nome_pais' => 'PAPUÁSIA-NOVA GUINÉ',
                    'name_pais' => 'PAPUA NEW GUINEA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 187,
                    'nome_pais' => 'PAQUISTÃO',
                    'name_pais' => 'PAKISTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 188,
                    'nome_pais' => 'PARAGUAI',
                    'name_pais' => 'PARAGUAY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 189,
                    'nome_pais' => 'PERU',
                    'name_pais' => 'PERU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 190,
                    'nome_pais' => 'POLINÉSIA FRANCESA',
                    'name_pais' => 'FRENCH POLYNESIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 191,
                    'nome_pais' => 'POLÓNIA',
                    'name_pais' => 'POLAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 192,
                    'nome_pais' => 'PORTO RICO',
                    'name_pais' => 'PUERTO RICO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 193,
                    'nome_pais' => 'PORTUGAL',
                    'name_pais' => 'PORTUGAL',
                    'moeda_sigla' => '€',
                    'status' => 1,
                    'timezone' => 'Europe/Lisbon',
                ],
[
                    'id_pais' => 194,
                    'nome_pais' => 'QUÉNIA',
                    'name_pais' => 'KENYA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 195,
                    'nome_pais' => 'QUIRGUIZISTÃO',
                    'name_pais' => 'KYRGYZSTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 196,
                    'nome_pais' => 'REINO UNIDO',
                    'name_pais' => 'UNITED KINGDOM',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => 'Europe/London',
                ],
[
                    'id_pais' => 197,
                    'nome_pais' => 'REPÚBLICA CHECA',
                    'name_pais' => 'CZECH REPUBLIC',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 198,
                    'nome_pais' => 'REPÚBLICA DOMINICANA',
                    'name_pais' => 'DOMINICAN REPUBLIC',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 199,
                    'nome_pais' => 'ROMÉNIA',
                    'name_pais' => 'ROMANIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 200,
                    'nome_pais' => 'RUANDA',
                    'name_pais' => 'RWANDA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 201,
                    'nome_pais' => 'RÚSSIA',
                    'name_pais' => 'RUSSIAN FEDERATION',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 202,
                    'nome_pais' => 'SAHARA OCCIDENTAL',
                    'name_pais' => 'WESTERN SAHARA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 203,
                    'nome_pais' => 'SALVADOR',
                    'name_pais' => 'EL SALVADOR',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 204,
                    'nome_pais' => 'SAMOA',
                    'name_pais' => 'SAMOA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 205,
                    'nome_pais' => 'SANTA HELENA',
                    'name_pais' => 'SAINT HELENA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 206,
                    'nome_pais' => 'SANTA LÚCIA',
                    'name_pais' => 'SAINT LUCIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 207,
                    'nome_pais' => 'SANTA SÉ',
                    'name_pais' => 'HOLY SEE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 208,
                    'nome_pais' => 'SÃO CRISTÓVÃO E NEVES',
                    'name_pais' => 'SAINT KITTS AND NEVIS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 209,
                    'nome_pais' => 'SÃO MARINO',
                    'name_pais' => 'SAN MARINO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 210,
                    'nome_pais' => 'SÃO PEDRO E MIQUELÃO',
                    'name_pais' => 'SAINT PIERRE AND MIQUELON',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 211,
                    'nome_pais' => 'SÃO TOMÉ E PRÍNCIPE',
                    'name_pais' => 'SAO TOME AND PRINCIPE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 212,
                    'nome_pais' => 'SÃO VICENTE E GRANADINAS',
                    'name_pais' => 'SAINT VINCENT AND THE GRENADINES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 213,
                    'nome_pais' => 'SEICHELES',
                    'name_pais' => 'SEYCHELLES',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 214,
                    'nome_pais' => 'SENEGAL',
                    'name_pais' => 'SENEGAL',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 215,
                    'nome_pais' => 'SERRA LEOA',
                    'name_pais' => 'SIERRA LEONE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 216,
                    'nome_pais' => 'SÉRVIA',
                    'name_pais' => 'SERBIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 217,
                    'nome_pais' => 'SINGAPURA',
                    'name_pais' => 'SINGAPORE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 218,
                    'nome_pais' => 'SÍRIA',
                    'name_pais' => 'SYRIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 219,
                    'nome_pais' => 'SOMÁLIA',
                    'name_pais' => 'SOMALIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 220,
                    'nome_pais' => 'SRI LANCA',
                    'name_pais' => 'SRI LANKA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 221,
                    'nome_pais' => 'SUAZILÂNDIA',
                    'name_pais' => 'SWAZILAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 222,
                    'nome_pais' => 'SUDÃO',
                    'name_pais' => 'SUDAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 223,
                    'nome_pais' => 'SUÉCIA',
                    'name_pais' => 'SWEDEN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 224,
                    'nome_pais' => 'SUÍÇA',
                    'name_pais' => 'SWITZERLAND',
                    'moeda_sigla' => 'SFr',
                    'status' => 1,
                    'timezone' => 'Europe/Zurich',
                ],
[
                    'id_pais' => 225,
                    'nome_pais' => 'SURINAME',
                    'name_pais' => 'SURINAME',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 226,
                    'nome_pais' => 'SVALBARD',
                    'name_pais' => 'SVALBARD',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 227,
                    'nome_pais' => 'TAILÂNDIA',
                    'name_pais' => 'THAILAND',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 228,
                    'nome_pais' => 'TAIWAN',
                    'name_pais' => 'TAIWAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 229,
                    'nome_pais' => 'TAJIQUISTÃO',
                    'name_pais' => 'TAJIKISTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 230,
                    'nome_pais' => 'TANZÂNIA',
                    'name_pais' => 'TANZANIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 231,
                    'nome_pais' => 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO',
                    'name_pais' => 'BRITISH INDIAN OCEAN TERRITORY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 232,
                    'nome_pais' => 'TERRITÓRIO DAS ILHAS HEARD E MCDONALD',
                    'name_pais' => 'HEARD ISLAND AND MCDONALD ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 233,
                    'nome_pais' => 'TIMOR-LESTE',
                    'name_pais' => 'TIMOR-LESTE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 234,
                    'nome_pais' => 'TOGO',
                    'name_pais' => 'TOGO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 235,
                    'nome_pais' => 'TOKELAU',
                    'name_pais' => 'TOKELAU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 236,
                    'nome_pais' => 'TONGA',
                    'name_pais' => 'TONGA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 237,
                    'nome_pais' => 'TRINDADE E TOBAGO',
                    'name_pais' => 'TRINIDAD AND TOBAGO',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 238,
                    'nome_pais' => 'TUNÍSIA',
                    'name_pais' => 'TUNISIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 239,
                    'nome_pais' => 'TURKS E CAICOS',
                    'name_pais' => 'TURKS AND CAICOS ISLANDS',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 240,
                    'nome_pais' => 'TURQUEMENISTÃO',
                    'name_pais' => 'TURKMENISTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 241,
                    'nome_pais' => 'TURQUIA',
                    'name_pais' => 'TURKEY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 242,
                    'nome_pais' => 'TUVALU',
                    'name_pais' => 'TUVALU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 243,
                    'nome_pais' => 'UCRÂNIA',
                    'name_pais' => 'UKRAINE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 244,
                    'nome_pais' => 'UGANDA',
                    'name_pais' => 'UGANDA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 245,
                    'nome_pais' => 'URUGUAI',
                    'name_pais' => 'URUGUAY',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 246,
                    'nome_pais' => 'USBEQUISTÃO',
                    'name_pais' => 'UZBEKISTAN',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 247,
                    'nome_pais' => 'VANUATU',
                    'name_pais' => 'VANUATU',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 248,
                    'nome_pais' => 'VENEZUELA',
                    'name_pais' => 'VENEZUELA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 249,
                    'nome_pais' => 'VIETNAME',
                    'name_pais' => 'VIETNAM',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 250,
                    'nome_pais' => 'WALLIS E FUTUNA',
                    'name_pais' => 'WALLIS AND FUTUNA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 251,
                    'nome_pais' => 'ZÂMBIA',
                    'name_pais' => 'ZAMBIA',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ],
[
                    'id_pais' => 252,
                    'nome_pais' => 'ZIMBABUÉ',
                    'name_pais' => 'ZIMBABWE',
                    'moeda_sigla' => null,
                    'status' => 0,
                    'timezone' => null,
                ]
        ];

        foreach ($rows as $row) {
            DB::table('regiao')->updateOrInsert(
                ['id_pais' => $row['id_pais']],
                $row
            );
        }
    }
}
